disabled_rules: [todo, trailing_whitespace]
opt_in_rules: [closure_spacing, collection_alignment, sorted_imports, explicit_init, fatal_error_message]
analyzer_rules: [unused_import]
included: [.]
excluded: [Carthage, Pods, .build, DerivedData]
line_length: { warning: 120, error: 160 }
type_body_length: { warning: 300, error: 400 }
file_length: { warning: 800, error: 1200 }
cyclomatic_complexity: { warning: 15, error: 25 }
force_cast: error
force_try: warning
trailing_comma:
  mandatory_comma: true 
